import { GoHomeFill } from 'react-icons/go';
import { IoIosSearch } from 'react-icons/io';
import { MdOutlineExplore } from 'react-icons/md';
import { RiMessengerLine } from 'react-icons/ri';
import { FaRegHeart } from 'react-icons/fa';
import { CgAddR } from 'react-icons/cg';
import { RxHamburgerMenu } from 'react-icons/rx';
import { FaThreads } from 'react-icons/fa6';
import { TbPhotoVideo } from 'react-icons/tb';
import { LuMessageCircle } from 'react-icons/lu';
import { IoPaperPlaneSharp } from 'react-icons/io5';
import { CiSaveUp2 } from 'react-icons/ci';
import { BsThreeDots } from 'react-icons/bs';
import { IoAddOutline } from 'react-icons/io5';

export const HomeIcon = GoHomeFill;
export const SearchIcon = IoIosSearch;
export const ExploreIcon = MdOutlineExplore;
export const MessageIcon = RiMessengerLine;
export const HeartIcon = FaRegHeart;
export const AddIcon = CgAddR;
export const ThreadIcon = FaThreads;
export const HamMenuIcon = RxHamburgerMenu;
export const ReelIcon = TbPhotoVideo;
export const CommentIcon = LuMessageCircle;
export const ShareIcon = IoPaperPlaneSharp;
export const SaveIcon = CiSaveUp2;
export const DotsIcon = BsThreeDots;
export const PostIcon = IoAddOutline;
